### ISSUE TITLE
Create Project in Repo and Branch Protection

### ISSUE THREAD

**Issue by toreylittlefield** [MacAndersonUche/pethealthreportservice#2]
@MacAndersonUche you're the repo owner so can you create a "Project" inside the repo so we can use a Kanban board? Can you also setup branch protection on `Main`. Thank you

 Also, since you're the repo owner and GH has limitations you'll have to be the one to manage the Settings and anything else we need like private variables to run in CI. Shouldn't be a lot though.

**Comment by MacAndersonUche** [comment]
I have done that

**Comment by toreylittlefield** [comment]
@MacAndersonUche thank you!
